/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF, Shadow } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		Mesh_sodaBottle: THREE.Mesh;
		Mesh_sodaBottle_1: THREE.Mesh;
	};
	materials: {
		brownDark: THREE.MeshStandardMaterial;
		red: THREE.MeshStandardMaterial;
	};
};

export function Advertising(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF("./models/bottle.gltf") as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Mesh_sodaBottle.geometry}
				material={materials.brownDark}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Mesh_sodaBottle_1.geometry}
				material={materials.red}
			/>
			<Shadow
				position={[0.05, -0.1, -0]}
				scale={0.25}
				opacity={0.6}
				rotation-y={-Math.PI / 12}
			/>
		</group>
	);
}

useGLTF.preload("./models/bottle.gltf");
