/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		Mesh_house_type03: THREE.Mesh;
		Mesh_house_type03_1: THREE.Mesh;
		Mesh_house_type03_2: THREE.Mesh;
		Mesh_house_type03_3: THREE.Mesh;
		Mesh_house_type03_4: THREE.Mesh;
	};
	materials: {
		["border.003"]: THREE.MeshStandardMaterial;
		["window.003"]: THREE.MeshStandardMaterial;
		["door.003"]: THREE.MeshStandardMaterial;
		["_defaultMat.003"]: THREE.MeshStandardMaterial;
		["roof.005"]: THREE.MeshStandardMaterial;
	};
};

export function Architecture(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF("./models/house.gltf") as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Mesh_house_type03.geometry}
				material={materials["border.003"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Mesh_house_type03_1.geometry}
				material={materials["window.003"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Mesh_house_type03_2.geometry}
				material={materials["door.003"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Mesh_house_type03_3.geometry}
				material={materials["_defaultMat.003"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Mesh_house_type03_4.geometry}
				material={materials["roof.005"]}
			/>
		</group>
	);
}

useGLTF.preload("./models/house.gltf");
