/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF, Shadow } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		Cube012: THREE.Mesh;
		Cube012_1: THREE.Mesh;
		Cube012_2: THREE.Mesh;
	};
	materials: {
		["Brown.018"]: THREE.MeshStandardMaterial;
		["White.040"]: THREE.MeshStandardMaterial;
		["Metal.083"]: THREE.MeshStandardMaterial;
	};
};

export function Education(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF("./models/book.gltf") as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group rotation={[Math.PI / 2, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube012.geometry}
					material={materials["Brown.018"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube012_1.geometry}
					material={materials["White.040"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube012_2.geometry}
					material={materials["Metal.083"]}
				/>
			</group>
			<Shadow
				position={[0, -0.15, -0.2]}
				scale={[0.475, 0.3, 0.1]}
				opacity={0.7}
				rotation-x={-Math.PI / 4}
			/>
		</group>
	);
}

useGLTF.preload("./models/book.gltf");
