/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF, Shadow } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		Invader: THREE.Mesh;
	};
	materials: {
		material: THREE.MeshStandardMaterial;
	};
};

export function Games(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF("./models/invader.gltf") as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.Invader.geometry} material={materials.material} />
			<Shadow position={[0, -2.65, 0]} scale={[4, 2, 2]} opacity={0.6} />
		</group>
	);
}

useGLTF.preload("./models/invader.gltf");
