/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: darkalphastudio (https://sketchfab.com/darkalphastudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/health-c3e36457c888481b936157249079ffdf
Title: Health
*/

import * as THREE from "three";
import { useGLTF, Shadow } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		Cube_Body_0: THREE.Mesh;
	};
	materials: {
		Body: THREE.MeshStandardMaterial;
	};
};

export function Health(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF("./models/health.glb") as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group scale={0.01}>
				<mesh
					geometry={nodes.Cube_Body_0.geometry}
					material={materials.Body}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={10}
				/>
			</group>
			<Shadow position={[0, -0.3, -0]} scale={0.3} opacity={0.6} />
		</group>
	);
}

useGLTF.preload("./models/health.glb");
