/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import * as THREE from "three";

type GLTFResult = GLTF & {
	nodes: {
		Plane: THREE.Mesh;
	};
};

export function Room(props: React.JSX.IntrinsicElements["group"]) {
	const { nodes } = useGLTF("./models/testRoom2.gltf") as GLTFResult;

	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.Plane.geometry}>
				<meshLambertMaterial color={0xcdcdcd} />
			</mesh>
		</group>
	);
}

useGLTF.preload("./models/testRoom2.gltf");
